CONFIG = {
    'accounts': {
        'chennairainsmod': {
            'consumer_key': '',
            'consumer_secret': '',
            'access_token': '',
            'access_token_secret': '',
            'tweets_per_hour': 200,
            },
    },
    'excluded_accounts': ['chennairainsmod', 'SWFireAndRescue'],
    'topics': ['#chennairains', '#chennaifloods', '#chennairainshelp', '#chennairescue', 
               'chennai', 'flood', 'tambaram', '#volunteerforchennai', '#chennaimicro',
               'mambalam', 'guindy', 'velachery', 'adyar', 'urappakkam', 'oorappakkam', 'oorapakkam',
               'urappakam', 'kelambakkam', 'siruseri', 'puzhal', 'anna nagar', 't nagar', 'chembarambakkam',
               'vandalur', 'gooduvanchery', 'guduvanchery', 'teynampet', 'ashok nagar', 'vadapalani',
               'chrompet', 'pallavaram', 'pozhichalur', 'sanatorium', 'madhavaram', 'mylapore', 'mandaveli',
               'thiruvottiyur', 'perambur', 'villivakkam', 'royappettah', 'egmore', 'purasawakkam', 'chennai airport',
               'kodambakkam', 'kotturpuram', 'triplicane', 'alwarpet' 'choolaimedu', 'kilpauk', 'mrc nagar',
               'santhome', 'padi', 'korattur', 'avadi', 'maduravoyal', 'koyambedu', 'kk nagar', 
               'saligramam', 'virugambakkam', 'valasaravakkam', 'alwarthirunagar', 'nandambakkam', 'ramapuram',
               'porur', 'poonamallee', 'meenambakkam', 'thiruvanmyur', 'saidapet', 'madippakkam', 'nanganallur',
               'pallikkaranai', 'thoraipakkam', 'medavakkam', 'adambakkam', 'nandambakkam',
               'cuddalore', '#savecuddalore', 'kanchipuram', 'thiruvallur', 'madipakkam', 'mogappair', 'karaikkal',
               'puduchery', 'pondicherry', 'pondy', 'nagappattinam'],
    'excluded_keywords': ['donate', 'report', 'follow', 'damage', 'organization',
                          'say', 'thoughts', 'prayers', 'efforts', 'learn',
                          'rescued', 'increase', 'rise',
                          'death toll', 'recovery', 'politics', 'tells', 'prayer', 'proud',
                          'struggles', 'solidarity', 'pray', 'bjp', 'dmk', 'admk', 'jayalalitha',
                          'congress', 'aap', 'submerged', 'south carolina', '#SWControl', 'london', 'wales',
                          'europe', 'skipton', 'carleton'],
    'keywords': ['food','water','medicine','danger','urgent',
                 'emergency','assist','necessary','medicines','rescue',
                 'need','emergency', 'volunteer','relief','meds','aid', 'seeking',
                 'hospital', 'immediate', 'boat', 'army', 'navy', 'transport',
                 'phone', 'mobile', 'ambulance', 'lorry', 'bus', 'shelter', 'verified'],
    'rabbitmq_config': {'host': 'localhost',
                        'queue': 'tweets'},
    'tweet_age': 6,
}
