CONFIG = {
    'consumer_key': '',
    'consumer_secret': '',
    'access_token': '',
    'access_token_secret': '',
    'topics': ['#nepalquake', '#nepalquakerelief', '#nepalearthquake',
               '#nepalquakerescue', '#nepalrescue', '#act4quake',
               '#helpnepal', '#earthquake', 'sindhupalchowk', 'sindhupalchok',
               'kathmandu', 'dhading', 'rasuwa', 'gorkha', 'nuwakot', 'ramechapp'],
    'excluded_keywords': ['donate', 'report', 'follow', 'damage', 'organization',
                          'say', 'thoughts', 'prayers', 'efforts', 'learn',
                          'rescued', 'recovered', 'evacuated', 'increase', 'rise',
                          'death toll', 'recovery', 'bjp', 'tells', 'prayer', 'proud',
                          'struggles', 'solidarity', 'baltimore'],
    'keywords': ['food','tent','water','medicine','danger','urgent',
                 'emergency','assist','necessary','medicines','rescue',
                 'need','clothe','clothes','volunteer','relief','meds','aid', 'seeking',
                 'hospital', 'immediate', 'sindhupalchowk', 'sindhupalchok', 'kathmandu',
                 'transport', 'dhading', 'rasuwa', 'gorkha', 'contact', 'nuwakot', 'send',
                 'ramechapp', ]
}
